module.exports={
    USERDATA:'user',
    PRODUCTDATA:'product',
    CATEGORYDATA:'category',
    CARTDATA:'cart',
    ADMIN:'admin',
    ORDER:'order',
    WISHLIST:'wishlist',
    BANNER:'banner',
    COMMINGSOON:'commingsoon',
    OFFERS:'offer',
    ADDRESS:'address',
    COUPON:'coupon'
}